export type BookingDetail = {
  id: number;
  booking_number: string;
  status: string;
  company_id?: number;
  has_shipment?: boolean;
  shipment_exists?: boolean;
  shipment_id?: number | null;
  created_at?: string;
  shipment_coverage?: string;
  pickup_date?: string | null;
  pickup_time?: string | null;
  pickup_notes?: string | null;
  delivery_notes?: string | null;
  activities?: Array<{ description?: string; event?: string; title?: string; created_at?: string; occurred_at?: string }>;
  origin_location_id?: number;
  destination_location_id?: number;
  transport_mode_id?: number;
  service_type_id?: number;
  container_type_id?: number | null;
  cargo_category_id?: number;
  dg_class_id?: number | null;
  container_responsibility?: string;
  company?: { name?: string; salesPic?: { name?: string }; sales_pic?: { name?: string } };
  shipper_location_id?: number | null;
  shipper_location?: { id?: number; name?: string };
  shipperLocation?: { id?: number; name?: string };
  consignee_type?: "customer_location" | "external" | string;
  consignee_location_id?: number | null;
  shipper_snapshot?: Record<string, unknown>;
  consignee_snapshot?: Record<string, unknown>;
  originLocation?: { id?: number; name?: string; code?: string };
  origin_location?: { id?: number; name?: string; code?: string };
  destinationLocation?: { id?: number; name?: string; code?: string };
  destination_location?: { id?: number; name?: string; code?: string };
  transportMode?: { id?: number; name?: string; code?: string };
  transport_mode?: { id?: number; name?: string; code?: string };
  serviceType?: { id?: number; name?: string; code?: string };
  service_type?: { id?: number; name?: string; code?: string };
  containerType?: { id?: number; name?: string; size?: string };
  container_type?: { id?: number; name?: string; size?: string };
  container_count: number;
  cargo_category?: { id?: number; name?: string; requires_temperature?: boolean; is_project_cargo?: boolean };
  cargoCategory?: { id?: number; name?: string; requires_temperature?: boolean; is_project_cargo?: boolean };
  estimated_weight?: number | null;
  estimated_cbm?: number | null;
  length?: number | null;
  width?: number | null;
  height?: number | null;
  departure_date?: string | null;
  cargo_description?: string;
  shipper_name?: string;
  shipper_address?: string;
  shipper_phone?: string;
  consignee_name?: string;
  consignee_address?: string;
  consignee_phone?: string;
  is_dangerous_goods: boolean | number;
  dg_class?: { id?: number; name?: string; code?: string };
  dgClass?: { id?: number; name?: string; code?: string };
  un_number?: string;
  msds_file?: string;
  equipment_condition?: string;
  temperature?: number | null;
  additional_services?: Array<{ id?: number | string; name?: string; code?: string }>;
  packages?: Array<Record<string, unknown>>;
  containers?: Array<Record<string, unknown>>;
  attachments?: Array<{
    id?: number;
    original_name?: string;
    original_filename?: string;
    document_type?: string | null;
    file_path?: string;
  }>;
  notes?: string;
  rejection_reason?: string;
  cancellation_reason?: string;
  customer_location_name?: string;
  shipper_company_name?: string;
  estimated_price?: string | number;
  price_breakdown?: {
    freight?: number;
    pickup?: number;
    delivery?: number;
    discount?: number;
    additional_services?: number;
    total?: number;
  };
};
