export type BookingDetail = {
  id: number;
  booking_number: string;
  status: string;
  has_shipment?: boolean;
  origin_location_id?: number;
  destination_location_id?: number;
  transport_mode_id?: number;
  service_type_id?: number;
  container_type_id?: number | null;
  cargo_category_id?: number;
  dg_class_id?: number | null;
  company?: { name?: string };
  originLocation?: { id?: number; name?: string; code?: string };
  origin_location?: { id?: number; name?: string; code?: string };
  destinationLocation?: { id?: number; name?: string; code?: string };
  destination_location?: { id?: number; name?: string; code?: string };
  transportMode?: { id?: number; name?: string; code?: string };
  transport_mode?: { id?: number; name?: string; code?: string };
  serviceType?: { id?: number; name?: string; code?: string };
  service_type?: { id?: number; name?: string; code?: string };
  containerType?: { id?: number; name?: string; size?: string };
  container_type?: { id?: number; name?: string; size?: string };
  container_count: number;
  cargo_category?: { id?: number; name?: string; requires_temperature?: boolean; is_project_cargo?: boolean };
  cargoCategory?: { id?: number; name?: string; requires_temperature?: boolean; is_project_cargo?: boolean };
  estimated_weight?: number | null;
  estimated_cbm?: number | null;
  length?: number | null;
  width?: number | null;
  height?: number | null;
  departure_date?: string | null;
  cargo_description?: string;
  shipper_name?: string;
  shipper_address?: string;
  shipper_phone?: string;
  consignee_name?: string;
  consignee_address?: string;
  consignee_phone?: string;
  is_dangerous_goods: boolean | number;
  dg_class?: { id?: number; name?: string; code?: string };
  dgClass?: { id?: number; name?: string; code?: string };
  un_number?: string;
  msds_file?: string;
  equipment_condition?: string;
  temperature?: number | null;
  additional_services?: Array<{ id?: number | string; name?: string; code?: string }>;
  notes?: string;
  rejection_reason?: string;
  estimated_price?: string | number;
};
